citation("minpack.lm")  # for Levenberg-Marquardt nlls fitting
citation('tidyverse')
citation('ggplot2')
citation('dplyr')
citation('growthcurver')
citation('stringr')
citation('taxize')
citation('nls.multstart')
citation('broom')
citation('growthcurver')
citation('cowplot')
citation('psych')
citation('MASS')
citation('fitdistrplus')
citation('directlabels')
